site_name: Automatic Code Documentation
theme:
  name: material
nav:
- Home: index.md
- Generated Docs:
  - Number_Guessing: generated/Number_guessing.md
  - Print_Name: generated/Print_name.md
  - Check_Even_Odd: generated/check_even_odd.md
  - Gen: generated/gen.md
